### ISSUE TITLE
Uncaught ReferenceError: pgRenderActions is not defined 

### ISSUE THREAD

**Issue by mucskaati** [Power-Components/livewire-powergrid#1689]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

```
livewire.js?id=923613aa:1124 Uncaught ReferenceError: pgRenderActions is not defined
    at [Alpine] pgRenderActions({ rowId: 13, parentI…), <anonymous>:3:16)
    at livewire.js?id=923613aa:1193:23
    at tryCatch (livewire.js?id=923613aa:1113:14)
    at evaluate (livewire.js?id=923613aa:1137:34)
    at Function.<anonymous> (livewire.js?id=923613aa:3548:17)
    at flushHandlers (livewire.js?id=923613aa:1278:48)
    at stopDeferring (livewire.js?id=923613aa:1283:7)
    at deferHandlingDirectives (livewire.js?id=923613aa:1286:5)
    at initTree (livewire.js?id=923613aa:1473:5)
    at livewire.js?id=923613aa:1425:7
```
    
```
    Uncaught ReferenceError: toHtml is not defined
    at [Alpine] toHtml (eval at safeAsyncFunction (livewire.js?id=923613aa:1171:21), <anonymous>:3:32)
    at livewire.js?id=923613aa:1193:23
    at tryCatch (livewire.js?id=923613aa:1113:14)
    at livewire.js?id=923613aa:3490:7
    at reactiveEffect (livewire.js?id=923613aa:2415:18)
    at Object.effect2 [as effect] (livewire.js?id=923613aa:2390:7)
    at effect (livewire.js?id=923613aa:763:35)
    at wrappedEffect (livewire.js?id=923613aa:779:29)
    at Function.<anonymous> (livewire.js?id=923613aa:3489:5)
    at flushHandlers (livewire.js?id=923613aa:1278:48)
```

### PHP Version

PHP 8.2.19

### PowerGrid

^6.0.0-beta4

### Laravel

^10.41

### Livewire

^3.5.6

### Theme

Bootstrap

### Describe the bug.

Hello,

After creating the powergrid, I get the following message in the console. Column hiding does not work on the datatable. Also when I try to use collapsable detail:

`PowerGrid::detail()
				->view('components.detail')
				->params(['name' => 'Luan'])
				->showCollapseIcon(),`

It throws an error:
`View [] not found.` But view exists in `views/components/detail.blade.php`

Thanks.

**Comment by luanfreitasdev** [comment]
Hello. Can you try again with beta 5?

Also, check out the new documentation

https://6x.livewire-powergrid.com/release-notes-and-upgrade/upgrade-guide.html

Thank you

**Comment by mucskaati** [comment]
@luanfreitasdev Thank you, I tried but the problems still persist. Errors from console disappear, but when I want to hide columns, it doesnt hide. Also when I want to export data it throws `Class "OpenSpout\Writer\XLSX\Options" not found`

When i want to add Detail `PowerGrid::detail()
				->view('components.detail')
				->params(['name' => 'Luan'])
				->showCollapseIcon(),`

 it also throws error: 
`View [] not found.`

Here is my UsersTable:

```<?php

namespace App\Livewire;

use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Button;
use PowerComponents\LivewirePowerGrid\Column;
use PowerComponents\LivewirePowerGrid\Facades\Filter;
use PowerComponents\LivewirePowerGrid\PowerGridFields;
use PowerComponents\LivewirePowerGrid\PowerGridComponent;
use PowerComponents\LivewirePowerGrid\Traits\WithExport;
use PowerComponents\LivewirePowerGrid\Components\SetUp\Exportable;
use PowerComponents\LivewirePowerGrid\Facades\PowerGrid;
use Illuminate\Contracts\View\{Factory, View};
use Illuminate\Foundation\Application;
use PowerComponents\LivewirePowerGrid\Facades\Rule;


final class UserTable extends PowerGridComponent
{

	use WithExport;

	public string $tableName = 'users-table';
	public string $primaryKey = 'id';
	public string $sortField = 'users.id';
	public bool $deferLoading = true;
	public bool $showGraph = true;

	public array $chartData = [
		'labels' => ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		'datasets' => [
			[
				'label' => 'Sales',
				'backgroundColor' => '#f87979',
				'data' => [12, 19, 3, 5, 2, 3, 11],
			]
		]
	];

	public function mount(): void
	{
		parent::mount();
	}

	private function getLabels()
	{
		$labels = [];
		for ($i = 0; $i < 12; $i++) {
			$labels[] = now()->subMonths($i)->format('M');
		}
		return $labels;
	}

	private function getRandomData()
	{
		$data = [];
		for ($i = 0; $i < count($this->getLabels()); $i++) {
			$data[] = rand(10, 100);
		}
		return $data;
	}

	public function setUp(): array
	{

		return [
			PowerGrid::header()
				->showSearchInput()
				->showToggleColumns(),
			PowerGrid::lazy()
				->rowsPerChildren(25),
			PowerGrid::footer()
				->showPerPage()
				->showRecordCount(),

			PowerGrid::exportable('export')
				->striped()
				->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),

			PowerGrid::detail()
				->view('components.detail')
				->showCollapseIcon()
				->params(['name' => 'Luan']),

		];
	}

	public function datasource(): Builder
	{
		return User::query();
	}

	public function relationSearch(): array
	{
		return [];
	}

	public function fields(): PowerGridFields
	{
		return PowerGrid::fields()
			->add('id')
			->add('name')

			/** Example of custom column using a closure **/
			->add('name_lower', fn(User $model) => strtolower(e($model->name)))

			->add('email')
			->add('language_id')
			->add('password_unhashed')
			->add('created_at_formatted', fn(User $model) => Carbon::parse($model->created_at)->format('d/m/Y H:i:s'));
	}

	public function columns(): array
	{
		return [
			Column::make('Id', 'id'),
			Column::make('Name', 'name')
				->sortable()
				->searchable(),

			Column::make('Email', 'email')
				->sortable()
				->searchable(),

			Column::make('Language id', 'language_id'),
			Column::make('Password unhashed', 'password_unhashed')
				->sortable()
				->searchable(),

			Column::make('Created at', 'created_at_formatted', 'created_at')
				->sortable(),

			Column::action('Action')
		];
	}

	public function header(): array
	{
		return [
			Button::add('bulk-delete')
				->slot('Bulk delete (<span x-text="window.pgBulkActions.count(\'' . $this->tableName . '\')"></span>)')
				->class('pg-btn-white dark:ring-pg-primary-600 dark:border-pg-primary-600 dark:hover:bg-pg-primary-700 dark:ring-offset-pg-primary-800 dark:text-pg-primary-300 dark:bg-pg-primary-700')
				->dispatch('bulkDelete.' . $this->tableName, []),
		];
	}

	#[On('bulkDelete.{tableName}')]
	public function bulkDelete(): void
	{
		$this->js('alert(window.pgBulkActions.get(\'' . $this->tableName . '\'))');
	}

	public function toggleGraph()
	{
		$this->showGraph = !$this->showGraph;
	}

	public function filters(): array
	{
		return [
			Filter::inputText('name')->operators(['contains']),
			Filter::inputText('email')->operators(['contains']),
			Filter::inputText('password_unhashed')->operators(['contains']),
			Filter::datetimepicker('created_at'),
		];
	}

	public function actions($row): array
	{
		return [
			Button::add('detail')
				->slot('Detail')
				->class('bg-blue-500 text-white font-bold py-2 px-2 rounded')
				->toggleDetail($row->id),
		];
	}

	public function actionRules(): array
	{
		return [
			Rule::rows()
				->when(fn($user) => $user->id == 1)
				->detailView('components.detail-rules', ['test' => 1]),
		];
	}
}
```

Thanks.

**Comment by luanfreitasdev** [comment]
Let's go :)

Could you let me know if you're testing this version in a new or existing project?

Could you let me know if you cleared all possible caches in Laravel? php artisan optimize:clear

Did you run npm install && npm run build ?

Could you generate a repository with this example if that doesn't work?

**Comment by mucskaati** [comment]
I am testing this version in existing project.
Yes, I cleared all possible caches - php artisan optimize:clear.
Yes, I run npm install and also build.

I don't know, because this is a project of a company that has signed a non-disclosure agreement with me. 

**UPDATE**
I create test laravel application from scratch with the same Laravel, Powergrid and Livewire versions and also mentioned issues persist. Also there is an issue with action button which doesnt show in datatable row. 

**Repo:**
https://github.com/mucskaati/datatable-example 

Thanks.

**Comment by luanfreitasdev** [comment]
Thank you for demo repo!

Fixed in v6.0.0-beta6

**Comment by luanfreitasdev** [comment]
Another bug (actions are not displaying correctly) has to do with the project setup and is not related to powergrid. See the online demo:

https://demo.livewire-powergrid.com

**Comment by mucskaati** [comment]
Thanks detail page is now working, but when I collapse and then uncollapse row, some data in row disappear (in my test repo: created at). Showing/hiding columns still doesnt work after update to beta6 and clearing cache. 

Can you please tell me what I have wrong with action buttons in my test repo? 

Thank you for responding so quickly.

**Comment by luanfreitasdev** [comment]
Hi, this is something that needs to be investigated, but I can see that it is working on the demo page.

Try following these steps in livewire installation:
- https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine

Also, remove published views

https://github.com/user-attachments/assets/3b9dc36e-898b-4450-b8ea-85f314cb8b61

https://demo.livewire-powergrid.com/examples/custom-field-image

**Comment by mucskaati** [comment]
Can you please investigate it for me? Thank you.  

**UPDATE**
If I have collection as datasource and I try to search, it throws error:

`Attempt to read property "searchable" on array`

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/pull/1699

**Comment by mucskaati** [comment]
**UPDATE**
Hello, 
I am here again :D

Caching data on deferLoading = true doesnt work

**Comment by backstageel** [comment]
I am also getting this error and had to rollback to V5
