### ISSUE TITLE
Property [$email] not found on component: [appointment-report-grid][Bug]: 

### ISSUE THREAD

**Issue by adebareshowemimo** [Power-Components/livewire-powergrid#883]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

4

### Laravel

9

### Theme

Bootstrap

### To Reproduce...

     return false;

    }

    public function __get($property)

    {

        $studlyProperty = str_replace(' ', '', ucwords(str_replace(['-', '_'], ' ', $property)));

        if (method_exists($this, $computedMethodName = 'get'.$studlyProperty.'Property')) {

            if (isset($this->computedPropertyCache[$property])) {

                return $this->computedPropertyCache[$property];

            }

            return $this->computedPropertyCache[$property] = app()->call([$this, $computedMethodName]);

        }

        throw new PropertyNotFoundException($property, static::getName());

    }

    public function __call($method, $params)

    {

        if (

            in_array($method, ['mount', 'hydrate', 'dehydrate', 'updating', 'updated'])

            || str($method)->startsWith(['updating', 'updated', 'hydrate', 'dehydrate'])

        ) {

            // Eat calls to the lifecycle hooks if the dev didn't define them.

            return;

        }

        if (static::hasMacro($method)) {

            return $this->macroCall($method, $params);

### Extra information

```markdown
return false;

    }



    public function __get($property)

    {

        $studlyProperty = str_replace(' ', '', ucwords(str_replace(['-', '_'], ' ', $property)));



        if (method_exists($this, $computedMethodName = 'get'.$studlyProperty.'Property')) {

            if (isset($this->computedPropertyCache[$property])) {

                return $this->computedPropertyCache[$property];

            }



            return $this->computedPropertyCache[$property] = app()->call([$this, $computedMethodName]);

        }



        throw new PropertyNotFoundException($property, static::getName());

    }



    public function __call($method, $params)

    {

        if (

            in_array($method, ['mount', 'hydrate', 'dehydrate', 'updating', 'updated'])

            || str($method)->startsWith(['updating', 'updated', 'hydrate', 'dehydrate'])

        ) {

            // Eat calls to the lifecycle hooks if the dev didn't define them.

            return;

        }



        if (static::hasMacro($method)) {

            return $this->macroCall($method, $params);
```

**Comment by luanfreitasdev** [comment]
Hello. Could you describe the problem better? Are you really using version 4?

**Comment by adebareshowemimo** [comment]
Yes

**Comment by adebareshowemimo** [comment]
@luanfreitasdev , the problem occurs when I try to implement inline editing using the code below. Once, I clicked on the enter button, it will throw the error. 


    public function onUpdatedToggleable(string $id, string $field, string $value): void
    {
        Appointment::query()->find($id)->update([
            $field => $value,
        ]);
    }

**Comment by adebareshowemimo** [comment]
@luanfreitasdev , here is a screencast showing the error ;

https://360.articulate.com/review/content/be864583-0a17-4ee1-b0f4-ca4e8a664f30/review

**Comment by adebareshowemimo** [comment]
I added this?  public ?string $email = null; 

A new error occurs :

Cannot auto-initialize an array inside property App\Http\Livewire\AppointmentReportGrid::$email of type ?string

**Comment by luanfreitasdev** [comment]
Hello!. The problem occurs because the property has to be defined as an array type. (This is wrong in the doc, I'll update it). Thanks

**Comment by luanfreitasdev** [comment]
![image](https://user-images.githubusercontent.com/33601626/226107463-ef1400f9-305b-47d5-ab5e-373fdb33a8b8.png)

**Comment by adebareshowemimo** [comment]
Many Thanks @luanfreitasdev . I have fixed the issues using the code below too :

 public $email = null;

    public function onUpdatedEditable($id, $field, $value): void
    {
        Appointment::query()->find($id)->update([
            $field => $value,
        ]);
    }

**Comment by MarkasCherry** [comment]
@luanfreitasdev docs are still not up-to-date, just spent couple hours trying to figure out this

**Comment by luanfreitasdev** [comment]
Sorry, I just corrected the doc
